# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0003_auto_20170307_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AddField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pnldata.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='purse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pnldata.Purse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pnldata.ExpenseSet'),
            preserve_default=False,
        ),
    ]
