# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0004_auto_20170307_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='currency',
        ),
    ]
