# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0006_auto_20170307_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pnldata.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='purse_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
