# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 16:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0007_auto_20170307_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='iso_code',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
