# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0010_auto_20170307_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='purse_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
