# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0011_auto_20170307_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpenseSet',
            new_name='Transaction',
        ),
    ]
