# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0012_auto_20170316_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='expense_set',
            new_name='transaction',
        ),
    ]
