# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pnldata', '0014_auto_20180301_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('date', 'currency')]),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=[b'date', b'currency'], name='pnldata_exc_date_d11c79_idx'),
        ),
    ]
